### ISSUE TITLE
old wiki links to correct github article

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/wiki-archive#1]
It would be very cool if the wiki links which are used in our documentation and handouts would still link to a working github wiki archive ... 

thanks in advance...

**Comment by dnsmichi** [comment]
This archive is meant to make the information available which is not horribly outdated. You may just copy such into your docs, or extract anything useful. The archive content is subject to change, and I wouldn't bet on linking here either. 

I'd suggest to update your documentation and add the missing content over there.
